SUPABASE_URL = "https://ldhifjmvjhpqplmchhni.supabase.co"
SUPABASE_KEY = "sb_publishable_M7yGx4CulLvcF6qd9QB7SA_lrAoHBTi"
GEMINI_API_KEY = "AIzaSyCDrk-_V6FH3Qeiw5BgqPLQ3p61fr__G7U"
#pswd: 5,8n!-4qq2LYCju